"use strict";
// Pure presentation checks; no browser dependency or connection to a real brain.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = vm.createContext({titles:{}, state:{}, Map, Set, Date});
vm.runInContext(fs.readFileSync('web/decisions.js','utf8'),context);
vm.runInContext(fs.readFileSync('web/activity.js','utf8'),context);
const command={kind:'decision_response',status:'queued'};
const present=(notification,activity,now=100)=>context.commandPresentation({...command,notification},activity,now);
assert.equal(present().label,'Answer saved');
assert.equal(present({status:'sending',attemptedAt:99}).label,'Notifying brain');
assert.equal(present({status:'sending',attemptedAt:1}).label,'Delivery unconfirmed');
assert.equal(present({status:'unavailable',detail:'Saved'}).label,'Notification unavailable');
assert.equal(present({status:'uncertain',detail:'Saved'}).label,'Delivery unconfirmed');
assert.equal(present({status:'accepted',finishedAt:99},{fresh:true,status:'idle'}).label,'Sent to Codex');
assert.equal(present({status:'accepted',finishedAt:99},{fresh:true,status:'running'}).label,'Brain active · awaiting receipt');
assert.equal(present({status:'accepted',finishedAt:99},{fresh:false,status:'running'}).label,'Sent to Codex');
assert.equal(present({status:'accepted',finishedAt:1}).label,'Receipt overdue');
const ended={status:'accepted',nativeDelivery:'owned_turn_start',nativeTurnStatus:'completed',finishedAt:1};
assert.equal(present(ended).label,'Native turn ended · receipt missing');
assert.match(present(ended).detail,/do not send a duplicate/);
assert.equal(present({...ended,nativeTurnStatus:'failed'}).label,'Native turn ended · receipt missing');
assert.equal(context.commandPresentation({...command,status:'processing',notification:{status:'uncertain'}}).label,'Received by brain');
assert.equal(context.commandPresentation({...command,status:'completed',result:'Retained outcome'}).detail,'Retained outcome');
vm.runInContext(fs.readFileSync('web/journey.js','utf8'),context);
vm.runInContext(fs.readFileSync('web/standard.js','utf8'),context);
const capabilityFailure=context.commandPresentation({kind:'standard_catalog_refresh',status:'failed',
  result:'Long private fixture diagnostic',catalogError:{code:'native_task_schema_unavailable',retryable:true}});
assert.equal(capabilityFailure.label,'Codex task tools are unavailable');
assert.match(capabilityFailure.detail,/phase review is unchanged/);
assert.ok(!capabilityFailure.detail.includes('Long private fixture diagnostic'),'Durable notices summarize instead of dumping the diagnostic');
assert.equal(context.commandPresentation({kind:'approve',status:'completed',needsBrainReceipt:true}).label,'Approval saved');
assert.equal(context.commandPresentation({kind:'listening',status:'completed',needsBrainReceipt:true,notification:{status:'accepted',finishedAt:99}},null,100).label,'Sent to Codex');
for(const kind of ['resume','reconcile','checkpoint','archive','brain_stop','brain_resume']) {
  assert.equal(context.commandPresentation({kind,status:'queued',notification:{status:'accepted',finishedAt:99}},null,100).label,'Sent to Codex');
}
assert.equal(context.activityLabel({fresh:false,lastKnownStatus:'idle'}),'Last observed idle');
assert.equal(context.activityLabel({fresh:false,lastKnownStatus:'running'}),'Last observed working');
assert.equal(context.activityLabel({fresh:false}),'Activity not observed');
context.state.meta={brainControl:{desired:'stopped',phase:'stop_requested'}};
assert.equal(context.commandPresentation(command).label,'Saved until brain resumes');
assert.equal(context.commandPresentation({kind:'brain_stop',status:'processing'}).label,'Preparing safe checkpoint');
assert.equal(context.brainControlPresentation(context.state.meta).label,'Stop requested');
assert.equal(context.dispatchPresentation({...context.state.meta,paused:true}).disabled,true);
context.state.meta.brainControl={desired:'stopped',phase:'parked',checkpoint:{at:99}};
assert.equal(context.brainControlPresentation(context.state.meta).label,'Safe checkpoint saved');
assert.equal(context.brainControlPresentation(context.state.meta,{lastKnownStatus:'idle',observedAt:98}).label,'Safe checkpoint saved');
assert.equal(context.brainControlPresentation(context.state.meta,{lastKnownStatus:'idle',observedAt:100}).label,'Safe checkpoint saved');
assert.equal(context.brainControlPresentation(context.state.meta,{fresh:true,status:'idle',observedAt:100}).label,'Brain stopped at checkpoint');
assert.equal(context.brainControlPresentation(context.state.meta,{lastKnownStatus:'running',observedAt:100}).label,'Safe checkpoint saved');
assert.equal(context.dispatchPresentation({paused:true},[{kind:'resume',status:'queued'}]).label,'Worker dispatch resume requested');
assert.equal(context.dispatchPresentation({paused:true},[{kind:'resume',status:'completed'}]).label,'New worker dispatch paused');
console.log('Decision, brain control and activity presentation checks passed');
const app=fs.readFileSync('web/app.js','utf8');
vm.runInContext(app.match(/function canArchiveWorker\(w\) \{[^\n]+\}/)[0],context);
const completeWorker={status:'complete',preserved:true,archived:false};
assert.equal(context.canArchiveWorker(completeWorker),true);
assert.equal(context.canArchiveWorker({...completeWorker,dispatchAdmission:{stage:'settled'}}),false);
assert.equal(context.canArchiveWorker({...completeWorker,status:'settled'}),false);
assert(app.includes('if(selected===w.id&&canArchiveWorker(w))'));
