"use strict";
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('web/assistant.js','utf8');
const start=source.indexOf('function assistantFailureNotice('),end=source.indexOf('function assistantStatus(',start);
assert(start>=0&&end>start);
const context={};vm.createContext(context);vm.runInContext(source.slice(start,end),context);
const notice=message=>context.assistantFailureNotice(message);
const timeout=notice('Inference timed out before a complete response. No automatic retry was sent.');
assert.match(timeout,/AI assistant timed out/);
assert.match(timeout,/not sent to the project brain/);
assert.match(timeout,/Try again later or use a project control/);
assert.equal((timeout.match(/No automatic retry was sent/g)||[]).length,1);
const busy=notice('Inference service is busy (429). Retry manually after 30 seconds; no automatic retry was sent.');
assert.equal((busy.match(/no automatic retry was sent/gi)||[]).length,1);
assert.match(busy,/Your question is still in the box/);
const unknown=notice('Assistant request failed.');
assert.equal((unknown.match(/No automatic retry was sent/g)||[]).length,1);
assert.match(source,/assistantStatus\(assistantFailureNotice\(error\.message\),true\)/);
console.log('Assistant error UI: single retry notice, retained question and clear timeout guidance passed');
const directStart=source.indexOf('function assistantDirectMessage('),directEnd=source.indexOf('function chatTurn(',directStart);
const previews=[],input={value:'  Explain the current blocker; do not start work.  '};
const direct={connected:true,assistantPending:false,$:()=>input,assistantRequestStep:(...args)=>previews.push(args)};
vm.createContext(direct);vm.runInContext(source.slice(directStart,directEnd),direct);
direct.assistantDirectMessage();
assert.deepEqual(previews,[['brain_message','Explain the current blocker; do not start work.']], 'Direct message only prepares the exact signed preview, without inference or submission');
direct.assistantPending=true;direct.assistantDirectMessage();
direct.assistantPending=false;direct.connected=false;direct.assistantDirectMessage();
direct.connected=true;input.value=' ';direct.assistantDirectMessage();
assert.equal(previews.length,1,'Busy, disconnected and empty messages cannot prepare a duplicate');
